version: '3'
services:
  redis:
    image: 'redis:3'
    ports:
      - '6379:6379'
  sut:
    build:
      context: .
      dockerfile: Dockerfile-test
    depends_on:
      - redis
    links:
      - redis
    environment:
      - redis__host=redis